# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af958ef55377bdfb0931e0bd4f0e2abfc7336c77348228cd7ca47628eb7a6ec3d1ceee70e03bd8c0503f750a07bf4e97c7a5d38ad9a9cf798e9970718d25fc57

test:
  secret_key_base: 299d7bdb6c7eca557b5e2d465cb8660d5aea44213f6bcd9103f332bb091fd6e859b74dd756403ec7aa576b6facca0aed7a8f1638b912fcb121bae5087c7de575

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
